name: deepl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - attr=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.0.90
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cycler=0.11.0
  - cython=0.29.32
  - dbus=1.13.18
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - gds-tools=1.5.0.59
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jack=1.9.21
  - jasper=2.0.33
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcups=2.3.3
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurl=7.87.0
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm10=10.0.1
  - libllvm15=15.0.6
  - libnghttp2=1.51.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnsl=2.0.0
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libogg=1.3.4
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsndfile=1.1.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.31.1
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - ncurses=6.3
  - nettle=3.8.1
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.82
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.6.0
  - openh264=2.3.1
  - openssl=3.0.7
  - p11-kit=0.24.1
  - packaging=22.0
  - pcre=8.45
  - pcre2=10.40
  - pillow=9.3.0
  - pip=22.3.1
  - pixman=0.40.0
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - py-opencv=4.6.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - qt-main=5.15.6
  - qt-webengine=5.15.4
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scipy=1.9.3
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.0
  - svt-av1=1.4.1
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - docopt==0.6.2
      - imageio==2.23.0
      - networkx==2.8.8
      - pycocotools==2.0.6
      - pywavelets==1.4.1
      - scikit-image==0.19.3
      - tifffile==2022.10.10
